Added 2 attempts with 30s delay while checking DB connection

diff --git a/bin/setup-config b/bin/setup-config
--- a/bin/setup-config
+++ b/bin/setup-config
@@ -14,23 +14,17 @@ chmod -R ug+w ${WWW_DIR}/app/etc
 
 echo "Initializing modules setup..."
 
-if [ ! -z "${M2SETUP_DB_HOST}" ]; then
-  echo Y | su www-data -s /bin/sh  -c "/usr/local/bin/php ${WWW_DIR}/bin/magento setup:config:set --db-host=${M2SETUP_DB_HOST}"
-fi
-if [ ! -z "${M2SETUP_DB_NAME}" ]; then
-  echo Y | su -s www-data /bin/sh -c "/usr/local/bin/php ${WWW_DIR}/bin/magento setup:config:set --db-name=${M2SETUP_DB_NAME}"
-fi
-if [ ! -z "${M2SETUP_DB_USER}" ]; then
-  echo Y | su www-data -s /bin/sh -c "/usr/local/bin/php ${WWW_DIR}/bin/magento setup:config:set --db-user=${M2SETUP_DB_USER}"
-fi
-if [ ! -z "${M2SETUP_DB_PASSWORD}" ]; then
-  echo Y | su www-data -s /bin/sh -c "/usr/local/bin/php ${WWW_DIR}/bin/magento setup:config:set --db-password=${M2SETUP_DB_PASSWORD}"
-fi
-if [ ! -z "${M2SETUP_ADMIN_URI}" ]; then
-  echo Y | su www-data -s /bin/sh -c "/usr/local/bin/php ${WWW_DIR}/bin/magento setup:config:set --backend-frontname=${M2SETUP_ADMIN_URI}" 
+if [ ! -z "${M2SETUP_DB_HOST}" ] && [ ! -z "${M2SETUP_DB_NAME}" ] && [ ! -z "${M2SETUP_DB_USER}" ] && [ ! -z "${M2SETUP_DB_PASSWORD}" ] && [ ! -z "${M2SETUP_ADMIN_URI}" ]; then
+  echo Y | su www-data -s /bin/sh  -c "/usr/local/bin/php ${WWW_DIR}/bin/magento setup:config:set --db-host=${M2SETUP_DB_HOST} --db-name=${M2SETUP_DB_NAME} --db-user=${M2SETUP_DB_USER} --db-password=${M2SETUP_DB_PASSWORD} --backend-frontname=${M2SETUP_ADMIN_URI}"
+else 
+  echo -e "Please specify all required variables: db-host, db-name, db-user, db-password, backend-frontname"
+  exit 10;
 fi
 if [ ! -z "${M2SETUP_BASE_URL}" ]; then
   echo Y | su www-data -s /bin/sh -c "/usr/local/bin/php ${WWW_DIR}/bin/magento setup:store-config:set --base-url=${M2SETUP_BASE_URL}"
+else
+  echo -e "Please specify base-url"
+  exit 10
 fi
 
 echo "Running Magento 2 modules setup script..."
